<a href="https://colab.research.google.com/github/NefChr/Test/blob/main/%CE%91%CE%BD%CF%84%CE%AF%CE%B3%CF%81%CE%B1%CF%86%CE%BF_Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  URL_Length  URL_Depth  Redirection  \
0        torcache.net        0        0           1          2            0   
1           giphy.com        0        0           1          2            1   
2     correios.com.br        0        0           1          4            0   
3    rocketnews24.com        0        0           1          2            0   
4  aijcs.blogspot.com        0        0           1          3            0   

   https_Domain  TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  \
0             0        0              0           0            0           1   
1             0        0              0           0            1           0   
2             0        0              0           0            1           1   
3             0        0              0           0            1           1   
4             0        1              0           1            1           1   

   Domain_End  iFrame  Mouse_Over  Right_Click  Web_Forwards  Label  
0           1       0           0            1             0      0  
1           1       0           0            1             0      0  
2           1       0           0            1             0      0  
3           1       0           0            1             0      0  
4           1       0           0            1             0      1

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          2            0             0   
1        0        0           1          2            1             0   
2        0        0           1          4            0             0   
3        0        0           1          2            0             0   
4        0        0           1          3            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            0           1           1   
1        0              0           0            1           0           1   
2        0              0           0            1           1           1   
3        0              0           0            1           1           1   
4        1              0           1            1           1           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             0  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [5]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [7]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [9]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.802
Precision: 0.8276896256163058
Recall: 0.802
F1 Score: 0.7971574857142857
Confusion Matrix:
[[1453   83]
 [ 511  953]]

SVC Metrics:
Accuracy: 0.8296666666666667
Precision: 0.8662964215087353
Recall: 0.8296666666666667
F1 Score: 0.8244971814195737
Confusion Matrix:
[[1520   16]
 [ 495  969]]

RandomForestClassifier Metrics:
Accuracy: 0.8633333333333333
Precision: 0.8727415730337079
Recall: 0.8633333333333333
F1 Score: 0.8621493584822897
Confusion Matrix:
[[1453   83]
 [ 327 1137]]

MLPClassifier Metrics:
Accuracy: 0.8503333333333334
Precision: 0.8699836617972023
Recall: 0.8503333333333334
F1 Score: 0.8478141994322459
Confusion Matrix:
[[1487   49]
 [ 400 1064]]

KNeighborsClassifier Metrics:
Accuracy: 0.834
Precision: 0.8364161814723008
Recall: 0.834
F1 Score: 0.8334757232992018
Confusion Matrix:
[[1355  181]
 [ 317 1147]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8606666666666667
Precision: 0.8711647559304925
Recall: 0.8606666666666667
F1

In [10]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.863333   0.872742  0.863333  0.862149
5  DecisionTreeClassifier  0.860667   0.871165  0.860667  0.859332
3           MLPClassifier  0.850333   0.869984  0.850333  0.847814
4    KNeighborsClassifier  0.834000   0.836416  0.834000  0.833476
1                     SVC  0.829667   0.866296  0.829667  0.824497
0      LogisticRegression  0.802000   0.827690  0.802000  0.797157
